services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ben
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: lapes_ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ben -d lapes_ecommerce"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8099:8099"
    environment:
      DATABASE_URL: postgres://ben:***@postgres:5432/lapes_ecommerce
      REDIS_URL: redis://redis:6379
      JWT_SECRET: lp2026...nge
      RUST_LOG: lapes_ecommerce_api=info,tower_http=info
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  pgdata:
